#!/usr/bin/env python3
"""Writes the table of the script commands of Fallout 3 and New Vegas as C++ data, from the CSV files that
dump_command_table.py makes of the two executables.

    scripts/openfallout/generate_command_table.py --fallout3 command_table_fo3.csv --newvegas command_table_fnv.csv \\
        --output components/falloutscript/vanillacommands.inc

Only the commands a compiled script can call (code 0x1000 or more) are kept; the block types and the console commands
(smaller codes) are left out. The table of New Vegas holds every command of Fallout 3 under the same code and name, so
the output has one entry per command of New Vegas, marks the ones Fallout 3 has, and gives the parameters of Fallout 3
for the few commands where they differ. The script stops with a message when the two tables disagree on a name, a short
name or whether the command is called on a reference, since the output could not say that.

With --conditions it also writes the types of the first two parameters of each function that a condition (CTDA) of a
record can name, one line for each command of New Vegas that has parameters. A condition names the function by its
number, which is the code of the command less 0x1000, and the loaders of records need the types to know which of the
two parameters are forms and so need their index adjusted for the load order.

Needs Python 3 only.
"""
import argparse
import csv
import sys

FIRST_COMMAND = 0x1000


def read_commands(path):
    """The script commands of a CSV file by code: (name, short name, needs reference, parameters, flags, parse)."""
    commands = {}
    with open(path, newline="") as stream:
        for line, row in enumerate(csv.reader(stream), 1):
            if not row:
                continue
            if len(row) not in (7, 8):
                raise SystemExit("%s line %d: %d fields, expected 7 or 8" % (path, line, len(row)))
            try:
                opcode = int(row[1], 0)
                needs_reference = int(row[4]) != 0
                flags = int(row[6], 0)
            except ValueError:
                raise SystemExit("%s line %d: not a command" % (path, line))
            if opcode < FIRST_COMMAND:
                continue
            if opcode in commands:
                raise SystemExit("%s line %d: code 0x%04X twice" % (path, line, opcode))
            commands[opcode] = (row[2], row[3], needs_reference, row[5].strip(), flags)
    return commands


def merge(fallout3, new_vegas):
    """A list of (code, name, short name, needs reference, flags, parameters, in Fallout 3, parameters in Fallout 3)."""
    rows = []
    for opcode in sorted(new_vegas):
        name, short_name, needs_reference, parameters, flags = new_vegas[opcode]
        in_fallout3 = opcode in fallout3
        fallout3_parameters = None  # the same as in New Vegas
        if in_fallout3:
            f_name, f_short, f_reference, f_parameters, f_flags = fallout3[opcode]
            if (f_name, f_short, f_reference) != (name, short_name, needs_reference):
                raise SystemExit(
                    "code 0x%04X is %s in Fallout 3 and %s in New Vegas, which the table can not hold"
                    % (opcode, (f_name, f_short, f_reference), (name, short_name, needs_reference))
                )
            if f_flags != flags:
                raise SystemExit("code 0x%04X (%s) has other flags in Fallout 3" % (opcode, name))
            if f_parameters != parameters:
                fallout3_parameters = f_parameters
        rows.append((opcode, name, short_name, needs_reference, flags, parameters, in_fallout3, fallout3_parameters))
    missing = sorted(set(fallout3) - set(new_vegas))
    if missing:
        raise SystemExit("Fallout 3 has commands that New Vegas lacks: " + " ".join("0x%04X" % m for m in missing))
    return rows


def quote(text):
    if any(c in text for c in '"\\') or any(ord(c) < 0x20 or ord(c) > 0x7E for c in text):
        raise SystemExit("unexpected character in %r" % text)
    return '"%s"' % text


def write(rows, stream):
    stream.write(
        "// Generated by scripts/openfallout/generate_command_table.py from the command tables in the executables of\n"
        "// Fallout 3 and New Vegas. Do not edit by hand.\n"
        "// code, name, short name, needs a reference, flags, parameters (New Vegas), in Fallout 3, parameters in\n"
        "// Fallout 3 when they differ (nullptr: the same)\n"
    )
    for opcode, name, short_name, needs_reference, flags, parameters, in_fallout3, fallout3_parameters in rows:
        stream.write(
            "{ 0x%04X, %s, %s, %s, 0x%X, %s, %s, %s },\n"
            % (opcode, quote(name), quote(short_name), "true" if needs_reference else "false", flags,
               quote(parameters), "true" if in_fallout3 else "false",
               "nullptr" if fallout3_parameters is None else quote(fallout3_parameters))
        )


def parameter_types(parameters):
    """The type numbers of a parameter string such as "50 1 1?", in order, without the marks of optional ones."""
    return [int(token.rstrip("?"), 0) for token in parameters.split()]


# The functions a condition can name that the table of commands of the executables has no entry for, because a script
# writes them another way (the variable of another script is `reference.variable`). Their parameters are those the
# community documentation of conditions gives: GetScriptVariable (an object, the index of a variable of its script)
# and GetQuestVariable (a quest, the index of a variable of its script). The number is the code less 0x1000.
CONDITION_ONLY = {53: (4, 22), 79: (14, 22)}


def condition_parameters(rows):
    """A list of (function number, type of the first parameter, type of the second or None) from the merged rows. The
    functions are New Vegas'; the first two parameters of the ones Fallout 3 has are the same."""
    found = {}
    for opcode, _name, _short_name, _needs_reference, _flags, parameters, _in_fallout3, _fallout3_parameters in rows:
        types = parameter_types(parameters)
        if types:
            found[opcode - FIRST_COMMAND] = (types[0], types[1] if len(types) > 1 else None)
    for function, types in CONDITION_ONLY.items():
        found.setdefault(function, types)
    return [(function, first, second) for function, (first, second) in sorted(found.items())]


def write_conditions(entries, stream):
    stream.write(
        "// Generated by scripts/openfallout/generate_command_table.py from the command tables in the executables of\n"
        "// Fallout 3 and New Vegas. Do not edit by hand.\n"
        "// function number of a condition (the code of the command less 0x1000), the types of its first two\n"
        "// parameters (0xFFFF: it has no second one)\n"
    )
    for function, first, second in entries:
        stream.write("{ %d, %d, %s },\n" % (function, first, "0xFFFF" if second is None else str(second)))


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--fallout3", required=True, help="the CSV of Fallout3.exe")
    parser.add_argument("--newvegas", required=True, help="the CSV of FalloutNV.exe")
    parser.add_argument("--output", required=True, help="the file to write")
    parser.add_argument("--conditions", help="also write the parameter types of the condition functions to this file")
    args = parser.parse_args(argv)
    rows = merge(read_commands(args.fallout3), read_commands(args.newvegas))
    with open(args.output, "w", newline="\n") as stream:
        write(rows, stream)
    if args.conditions:
        entries = condition_parameters(rows)
        with open(args.conditions, "w", newline="\n") as stream:
            write_conditions(entries, stream)
        print("wrote the parameters of %d condition functions to %s" % (len(entries), args.conditions))
    print("wrote %d commands (%d in Fallout 3) to %s" % (len(rows), sum(1 for r in rows if r[6]), args.output))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
