#ifndef OPENFALLOUT_COMPONENTS_PLATFORM_PLATFORM_HPP
#define OPENFALLOUT_COMPONENTS_PLATFORM_PLATFORM_HPP

namespace Platform
{

    void init();

}

#endif // OPENFALLOUT_COMPONENTS_PLATFORM_PLATFORM_HPP
